In [1]:
import torch


In [2]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())

1.13.1
True


In [3]:
a=1;


In [4]:
char a='a'

SyntaxError: invalid syntax (940410102.py, line 1)

In [ ]:
a

In [ ]:
print(a)


In [ ]:
list=[1,2,3,4]
print(list)

In [ ]:
list(2)


In [ ]:
list[2]


In [ ]:
user = {}
user['age']=25
user['address']='seoul'

print(user)
print(user.get('age'))

In [ ]:
if user.get('age')==1:
    print('true')
elif user.get('age')==2:
    print('mid')
else:
    print('age is', user.get('age'))

In [ ]:
list=[1,2,3,4,5,6,7,8,9]

for num in list:
    if num%2 != 1:
        print(list[num-1])
    if num == 7:
        break


In [ ]:
sum=0
for i in range(10):
    if i%2 == 0:
        sum = sum + i

print(sum)

In [ ]:
a=[1,2,3,4]
result=[]

print(result)
for num in a:
    result.append(num*3)

print(result)

In [ ]:
result = [num*2 for num in a]

In [ ]:
a=(1,2,3)

In [ ]:
s1 = set('Hello')
print(s1)
l1 = tuple(s1)
print(l1)
print(l1[0])

In [ ]:
s1={1,2,3,4,5}
s2={4,2,45,6}

s1&s2
s1-s2
s2-s1

id(s1)

In [9]:
import numpy as np
import math

x = np.linspace(-math.pi, math.pi, 2000)
y = np.sin(x)

a = np.random.randn()
b = np.random.randn()
c = np.random.randn()
d = np.random.randn()

learning_rate = 1e-6
for t in range(2000):
    # Forward propagate
    y_pred = a + b*x + c*x**2 + d*x**3

    # Loss
    loss = np.square(y_pred - y).sum()
    if t%100 == 99:
        print(t,loss)

    grad_y_pred = 2.0*(y_pred - y)
    grad_a = grad_y_pred.sum()
    grad_b = (grad_y_pred*x).sum()
    grad_c = (grad_y_pred*x**2).sum()
    grad_d = (grad_y_pred*x**3).sum()
    
    a -= learning_rate*grad_a
    b -= learning_rate*grad_b
    c -= learning_rate*grad_c
    d -= learning_rate*grad_d
    
print(f'Result: y = {a}+{b}x+{c}x^2+{d}x^3')


99 3310.324353641294
199 2195.9548792382484
299 1457.9052578678989
399 969.038671654909
499 645.1874050761481
599 430.62449903900955
699 288.4502200122388
799 194.2290384338759
899 131.7777824179421
999 90.37751286706484
1099 62.92772364761923
1199 44.72428348137634
1299 32.65027232831941
1399 24.64015934117053
1499 19.324950898239756
1599 15.797162875182423
1699 13.455138340098241
1799 11.899911413153845
1899 10.866873182578932
1999 10.180490040607888
Result: y = -0.011657821782762753+0.8224822327168196x+0.0020111682445183706x^2+-0.0884574000439243x^3


In [10]:
import torch
import math


dtype = torch.float
device = torch.device("cpu")
# device = torch.device("cuda:0") # GPU에서 실행하려면 이 주석을 제거하세요

# 무작위로 입력과 출력 데이터를 생성합니다
x = torch.linspace(-math.pi, math.pi, 2000, device=device, dtype=dtype)
y = torch.sin(x)

# 무작위로 가중치를 초기화합니다
a = torch.randn((), device=device, dtype=dtype)
b = torch.randn((), device=device, dtype=dtype)
c = torch.randn((), device=device, dtype=dtype)
d = torch.randn((), device=device, dtype=dtype)

learning_rate = 1e-6
for t in range(2000):
    # 순전파 단계: 예측값 y를 계산합니다
    y_pred = a + b * x + c * x ** 2 + d * x ** 3

    # 손실(loss)을 계산하고 출력합니다
    loss = (y_pred - y).pow(2).sum().item()
    if t % 100 == 99:
        print(t, loss)

    # 손실에 따른 a, b, c, d의 변화도(gradient)를 계산하고 역전파합니다.
    grad_y_pred = 2.0 * (y_pred - y)
    grad_a = grad_y_pred.sum()
    grad_b = (grad_y_pred * x).sum()
    grad_c = (grad_y_pred * x ** 2).sum()
    grad_d = (grad_y_pred * x ** 3).sum()

    # 가중치를 갱신합니다.
    a -= learning_rate * grad_a
    b -= learning_rate * grad_b
    c -= learning_rate * grad_c
    d -= learning_rate * grad_d


print(f'Result: y = {a.item()} + {b.item()} x + {c.item()} x^2 + {d.item()} x^3')

99 1067.6773681640625
199 726.5357666015625
299 495.8260803222656
399 339.6388854980469
499 233.79122924804688
599 161.9816131591797
699 113.21117401123047
799 80.05138397216797
899 57.480194091796875
999 42.099098205566406
1099 31.60577964782715
1199 24.43873405456543
1299 19.538021087646484
1399 16.183103561401367
1499 13.883712768554688
1599 12.306010246276855
1699 11.222232818603516
1799 10.476919174194336
1899 9.963796615600586
1999 9.610132217407227
Result: y = 0.02436739020049572 + 0.8409761786460876 x + -0.004203781485557556 x^2 + -0.09108799695968628 x^3


In [11]:
# -*- coding: utf-8 -*-
import torch
import math

# 입력값과 출력값을 갖는 텐서들을 생성합니다.
x = torch.linspace(-math.pi, math.pi, 2000)
y = torch.sin(x)

# 이 예제에서, 출력 y는 (x, x^2, x^3)의 선형 함수이므로, 선형 계층 신경망으로 간주할 수 있습니다.
# (x, x^2, x^3)를 위한 텐서를 준비합니다.
p = torch.tensor([1, 2, 3])
xx = x.unsqueeze(-1).pow(p)

# 위 코드에서, x.unsqueeze(-1)은 (2000, 1)의 shape을, p는 (3,)의 shape을 가지므로,
# 이 경우 브로드캐스트(broadcast)가 적용되어 (2000, 3)의 shape을 갖는 텐서를 얻습니다.

# nn 패키지를 사용하여 모델을 순차적 계층(sequence of layers)으로 정의합니다.
# nn.Sequential은 다른 Module을 포함하는 Module로, 포함되는 Module들을 순차적으로 적용하여 
# 출력을 생성합니다. 각각의 Linear Module은 선형 함수(linear function)를 사용하여 입력으로부터
# 출력을 계산하고, 내부 Tensor에 가중치와 편향을 저장합니다.
# Flatten 계층은 선형 계층의 출력을 `y` 의 shape과 맞도록(match) 1D 텐서로 폅니다(flatten).
model = torch.nn.Sequential(
    torch.nn.Linear(3, 1),
    torch.nn.Flatten(0, 1)
)

# 또한 nn 패키지에는 주로 사용되는 손실 함수(loss function)들에 대한 정의도 포함되어 있습니다;
# 여기에서는 평균 제곱 오차(MSE; Mean Squared Error)를 손실 함수로 사용하겠습니다.
loss_fn = torch.nn.MSELoss(reduction='sum')

learning_rate = 1e-6
for t in range(2000):

    # 순전파 단계: x를 모델에 전달하여 예측값 y를 계산합니다. Module 객체는 __call__ 연산자를 
    # 덮어써서(override) 함수처럼 호출할 수 있도록 합니다. 이렇게 함으로써 입력 데이터의 텐서를 Module에 전달하여
    # 출력 데이터의 텐서를 생성합니다.
    y_pred = model(xx)

    # 손실을 계산하고 출력합니다. 예측한 y와 정답인 y를 갖는 텐서들을 전달하고,
    # 손실 함수는 손실(loss)을 갖는 텐서를 반환합니다.
    loss = loss_fn(y_pred, y)
    if t % 100 == 99:
        print(t, loss.item())

    # 역전파 단계를 실행하기 전에 변화도(gradient)를 0으로 만듭니다.
    model.zero_grad()

    # 역전파 단계: 모델의 학습 가능한 모든 매개변수에 대해 손실의 변화도를 계산합니다.
    # 내부적으로 각 Module의 매개변수는 requires_grad=True일 때 텐서에 저장되므로,
    # 아래 호출은 모델의 모든 학습 가능한 매개변수의 변화도를 계산하게 됩니다.
    loss.backward()

    # 경사하강법을 사용하여 가중치를 갱신합니다.
    # 각 매개변수는 텐서이므로, 이전에 했던 것처럼 변화도에 접근할 수 있습니다.
    with torch.no_grad():
        for param in model.parameters():
            param -= learning_rate * param.grad

# list의 첫번째 항목에 접근하는 것처럼 `model` 의 첫번째 계층(layer)에 접근할 수 있습니다.
linear_layer = model[0]

# 선형 계층에서, 매개변수는 `weights` 와 `bias` 로 저장됩니다.
print(f'Result: y = {linear_layer.bias.item()} + {linear_layer.weight[:, 0].item()} x + {linear_layer.weight[:, 1].item()} x^2 + {linear_layer.weight[:, 2].item()} x^3')

99 822.05419921875
199 552.4039306640625
299 372.392578125
399 252.15301513671875
499 171.79052734375
599 118.0466079711914
699 82.0804443359375
799 57.99516677856445
899 41.854530334472656
999 31.029987335205078
1099 23.764986038208008
1199 18.88517189025879
1299 15.604680061340332
1399 13.397409439086914
1499 11.910958290100098
1599 10.909008026123047
1699 10.23299789428711
1799 9.776453018188477
1899 9.467829704284668
1999 9.2589750289917
Result: y = 0.014050330966711044 + 0.8408982157707214 x + -0.002423916244879365 x^2 + -0.09107691049575806 x^3


In [14]:
from PIL import Image

image = Image.open("yorkie.jpg")
image.show()

In [36]:
t = int(input())
while t > 0:
    print(t, ' ')
    t -= 1



2  
1  


In [26]:
import numpy as np

zero = np.zeros([3,3])
print(zero)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
FF